### ISSUE TITLE
java版本大于11都会报错，好像不支持高版本

### ISSUE THREAD

**Issue by godzeo** [fofapro/fofa-java#5]
![image](https://user-images.githubusercontent.com/64398024/104296610-d1021b00-54fc-11eb-857e-1100e133fc7b.png)

**Comment by godzeo** [comment]
sun.misc.BASE64Encoder 版本问题 不建议使用java.sun自带包

**Comment by xxxxbxxxxx** [comment]
仅在jdk11 会出现该问题吗？别的版本有吗？

**Comment by godzeo** [comment]
> 仅在jdk11 会出现该问题吗？别的版本有吗？

应该是大于9都会，因为自带的包变了

**Comment by xxxxbxxxxx** [comment]
预计这周发行新版本修复该问题，不过目前来说不建议在高版本的JDK运行。

**Comment by xxxxbxxxxx** [comment]
Base64问题已经修复，请升级到1.0.3.RELEASE
