### ISSUE TITLE
查询字段校验不全

### ISSUE THREAD

**Issue by retnullyu** [fofapro/fofa-java#7]
希望filds参数校验的时候加上所有官方字段。可选的列表有：host title ip domain port country province city country_name header server protocol banner cert isp as_number as_organization latitude longitude structinfo icp fid cname type jarm

**Comment by xxxxbxxxxx** [comment]
迭代升级，可自定义扩展字段

**Comment by xxxxbxxxxx** [comment]
> 希望filds参数校验的时候加上所有官方字段。可选的列表有：host title ip domain port country province city country_name header server protocol banner cert isp as_number as_organization latitude longitude structinfo icp fid cname type jarm

已经添加，在使用时也可通过以下代码动态添加：
```java
FofaConstants.SEARCH_ALL_FIELDS_LIST.add("host");
```
